# Generated by Django 3.2.7 on 2021-09-28 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FCSApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Age',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='FriendRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Friend1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Friend1_set', to='FCSApp.customer')),
                ('Friend2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Friend2_set', to='FCSApp.customer')),
            ],
        ),
    ]
