# Generated by Django 3.2.7 on 2021-09-30 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FCSApp', '0002_auto_20210929_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('photography', models.CharField(max_length=100)),
                ('Healthansfitness', models.CharField(max_length=150)),
                ('Mentorship', models.CharField(max_length=200)),
                ('Gardening', models.CharField(max_length=200)),
                ('Sports', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
