# Generated by Django 3.2.7 on 2021-10-13 11:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FCSApp', '0003_interest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='photography',
        ),
        migrations.AddField(
            model_name='interest',
            name='Photography',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=10),
        ),
        migrations.AlterField(
            model_name='interest',
            name='Gardening',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=10),
        ),
        migrations.AlterField(
            model_name='interest',
            name='Healthansfitness',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=10),
        ),
        migrations.AlterField(
            model_name='interest',
            name='Mentorship',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=10),
        ),
        migrations.AlterField(
            model_name='interest',
            name='Sports',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=10),
        ),
        migrations.RemoveField(
            model_name='interest',
            name='user',
        ),
        migrations.AddField(
            model_name='interest',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
